S7App/urls.py
from django.urls import path
from . import views

app_name = 'S7App'

urlpatterns = [
    path('', views.home, name='home'),
    path('about-me/', views.about, name='about'),
    path('my-profile/', views.profile, name='profile'),
    path('contacts/', views.contacts, name='contacts'),
]

S7project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('S7App.urls', namespace="S7App")),
]

S7App/models.py
from django.db import models

# Create your models here.

S7App/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def profile(request):
    return render(request, 'profile.html')

def contacts(request):
    return render(request, 'contacts.html')

S7App/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html>
	<head>
		<title>ABOUT ME</title>
	</head>
	
	<body>
	
		<div class="container2" style="margin-top: 30px;">
			<div class="row">
				<div class="col-md-4" style="margin-top: 35px;">
					<img src="{% static 'images/scenery.jpg' %}" id="scenery"/>
					<h2 id="quote"><strong>I Like to be Adventurous<br>
						& See the World Through<br>Various Perspectives</strong></h2>
				</div>
				<div class="col-md-4" style="margin-top: 35px;">
					<div class="col">
						<div class="row-md-2">
							<h3 class="desc-head"><strong>&#128154 I Am a Dedicated Person.</strong></h3>
							<p class="content-desc">I'm a highly dedicated person. I sometimes even
							risk my health to finish the job I am responsible of. It's very important
							for me to dedicate myself to do something I am responsible of for the sake of
							common goods.</p>
						</div>
						<div class="row-md-2">
							<h3 class="desc-head"><strong>&#127759 I Am an Environmentalist.</strong></h3>
							<p class="content-desc">When you claim yourself as an environmantalist,
							you need to be truly care about the environment and start by doing
							some little and meaningful things to save the earth!</p>
						</div> 
						<div class="row-md-2">
							<h3 class="desc-head"><strong>&#128444 I Express My Creativity Through Designs.</strong></h3>
							<p class="creativity-desc">I've been into designs since
								I was a sophomore in high school. And since I also study
								computer science, I'm aspired to put my sense of aesthetic-ness
								into digital product designs.</p> 
						</div>
					</div>
				</div>
				<div class="col-md-4" style="margin-top: 35px;">
					<div class="col">
						<div class="row-md-2">
							<h3 class="desc-head"><strong>&#127926 I Love Alternative Musics.</strong></h3>
							<p class="content-desc">I love alternative/indie and RnB musics. Yes, my music taste is
							a little bit anti-mainstream. My favourite kind of bands/musicians are something like
							LANY, Honne, The 1975, The Japanese House, Girl in Red, Declan McKenna, Frank Ocean, SZA,
							Alextbh, etc.</p>
						</div>
						<div class="row-md-2">
							<h3 class="desc-head"><strong>&#9992 I Like to Travel.</strong></h3>
							<p class="content-desc">Travelling could be very exciting for me.
							I could bump into my peace of mind. Besides that,
							going back to nature can make me learn to appreciate life more by
							seeing the world from different perspectives.</p>
						</div> 
						<div class="row-md-2">
							<h3 class="desc-head"><strong>&#128123 I Am Into Horror Stuff.</strong></h3>
							<p class="content-desc">Meanwhile most of my friends find horror/thriller stuff,
							such as horror/thriller movies, books, or short story scary, I find them
							intriguing! It's always exciting for me to read horror stories,
							especially the ones that are based on true events like Cermis UI.</p> 
						</div>
					</div>
				</div>
			</div>
		</div>
	</body>
</html>

{% endblock %}

S7App/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <link rel="stylesheet" id="theme" href="{% static 'css/style.css' %}" title="light" />
        <link rel="stylesheet" id="theme" href="{% static 'css/alt-style.css' %}" title="dark" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"> </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="/static/js/script.js"></script>
    </head>
    
  <body id="bod">
        <nav class="navbar fixed-top navbar-expand-lg navbar-light">
            <a class="navbar-brand" style="font-size: 20px;" href="">&#x1F469;&#x1F3FB;&#x200D;&#x1F4BB;</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse" id="navbarNav">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'S7App:home' %}" style="color: white;">HOME<span class="sr-only"></span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'S7App:about' %}" style="color: white;">ABOUT ME</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'S7App:profile' %}" style="color: white;">MY PROFILE</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'S7App:contacts' %}" style="color: white;">CONTACTS</a>
                    </li>
                </ul>
                <div class="right">
                    <span class="navbar-text" style="text-align: end; color: white;">
                        THEME :
                    </span>
                    <button class="btn" id="light" title="Light Mode" style="font-size: 21px;" onclick="switch_style('light');return false;" name="theme" value="Light Theme">&#127774</button>
                    <button class="btn" id="dark" title="Dark Mode" style="font-size: 20px;" onclick="switch_style('dark');return false;" name="theme" value="Dark Theme">&#x1F31B</button>
                </div>
            </div>
        </nav>

        {% block content %}
	
    	{% endblock %}
  
    </body>
</html>

S7App/templates/contacts.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html>
	<head>
		<title>CONTACT ME</title>
	</head>
	
	<body>
	
		<div class="container4" style="margin-top: 30px;">		
			<div class="row">
				<div class="col-md-6" style="height: 560px">
					<h1 id="text">Let's Get in Touch!<br>Find Me on:</h1>
				</div>
				<div class="col-sm-6" style="height: 560px">
					<div class="components">
						<p class="link"><a href="https://www.linkedin.com/in/kirana-alfatianisa-1b2852185/" target="_blank"><img alt="linkedin" style="vertical-align: middle;
						margin-left: 12px; height:70px" src="{% static 'images/altlinkedin.png' %}"/><span style="font-size: 28px; margin-left: 12px">Kirana Alfatianisa</span></a></p>
						<p class="link"><a href="https://instagram.com/kiralft" target="_blank"><img alt="insta" style="vertical-align: middle; margin-left: 11px; height:75px"
						src="{% static 'images/igalt.png' %}"/><span style="font-size: 28px; margin-left: 13px;">kiralft</span></a></p>
						<p class="link"><a href="mailto: alfatianisa@gmail.com" target="_blank"><img alt="gmail" style="vertical-align: middle; height:70px; margin-left: 12px"
						src="{% static 'images/mail.png' %}"/><span style="font-size: 28px; margin-left: 12px;">alfatianisa@gmail.com</span></a></p>
					</div>
				</div>
			</div>
			<div class="row-md-1">
				<h3 id="copyright"><strong>Kirana Alfatianisa &copy 2019</strong></h3>
			</div>
		</div>
	</body>
</html>

{% endblock %}

S7App/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html>
	<head>
		<title>HOME</title>
	</head>
	
	<body>

		<div class = "container" style="margin-top: 30px;">
			<div class="row">
				<div class="col-sm-7">
					<h1 id="hello"><strong>HELLO!&#x1f44b </strong><br>My Name is<br>Kirana Alfatianisa.</h1>
					<p id="desc">I'm a graphic and web design enthusiast.<br> I'm currently in my sophomore year of studying computer<br>
						science at University of Indonesia and really aspired to be a<br>
						front end developer or data analyst in the near future!</p>
				</div>
				<div class="col-sm-5" >
					<img src="{% static 'images/me.jpg' %}" alt="self picture" id="mypic"/>
				</div>
			</div>
		</div>
	</body>
</html>

{% endblock %}

S7App/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html>
	<head>
		<title>MY PROFILE</title>
	</head>
	
	<body>
		<div class="container3" style="margin-top: 60px;">
			<div class="row">
				<div class="col-md-5">
					<div id="headd" style="margin-top: 35px;">
						<h1 id="name"><strong>Kirana Alfatianisa</strong></h1>
						<h3 id="date">Sophomore at University of Indonesia<br>
						Born in Jakarta, August 12, 2000</h3>
						<h2 id="dots"> .               .               .    </h2>
					</div>
				</div>
				<div class="col-md-7">
					<h2 class="emojis" style="margin-top: 35px;">&#127891  &#127942  &#128203  &#9881</h2>
				</div>
			</div>

			<div class="row">
				<div class="col-md-4">
					<div class="col" id="accordion">
						<button class="accordion"><strong>Recent  Activities</strong></button>
							<div class="panel">
						  		<p style="text-align: justify;">I am currently on my 3rd semester of studying computer science in University of Indonesia.
									  My recent activities are mostly studying, working on assignments, listening to music,
									  or complaining about my sleep deprivation. Being a 3rd semester CS major in UI sucks
									  my soul out slowly lol. 
								</p>
							</div>
						<button class="accordion"><strong>Education</strong></button>
							<div class="panel">
								<ul class="educations">
									<li class="edu">
										<p>SD Negeri Cipedak 03 (2006-2012)</p>
									</li>
									<li class="edu">
										<p>SMP Negeri 85 Jakarta (2012-2015)</p>
									</li>
									<li class="edu">
										<p>SMA Negeri 28 Jakarta (2015-2018)</p>
									</li>
									<li class="edu">
										<p>Faculty of Computer Science,
										University of Indonesia (2018-now)</p>
									</li>
								</ul>
							</div>
						<button class="accordion"><strong>Achievements</strong></button>
							<div class="panel">
								<ul class="achievements">
									<li class="achv">
										<p>2nd Place at 8 Research Competition (2016)</p>
									</li>
									<li class="achv">
										<p>2nd Runner Up at KIR Jakarta Selatan Research Paper Competition (2016)</p>
									</li>
								</ul>
							</div> 
					</div>
				</div>
				<div class="col-md-4">
					<h2 id="exp">Experiences:</h2>
					<ul class="experiences">
						<li class="expr">
							<p>Creative & Documentation Staff of Science Class SMAN 28 Jakarta (2015)</p>
						</li>
						<li class="expr">
							<p>PIC of Design & Decoration at Science Class SMAN 28 Jakarta (2016)</p>
						</li>
						<li class="expr">
							<p>PIC of Science Project Competition at Robotic Day (2017)</p>
						</li>
						<li class="expr">
							<p>Deputy of Technological Applications at KIR SMAN 28 Jakarta (2016-2017)</p>
						</li>
						<li class="expr">
							<p>Liaison Officer at OIM UI 2018 (2018)</p>
						</li>
						<li class="expr">
							<p>Secretary Staff at COMPFEST 11 (2019)</p>
						</li>
						<li class="expr">
							<p>Staff of Entrepreneurship Division at DPM Fasilkom UI</p>
						</li>
					</ul>
				</div>
				<div class="col-md-4">
					 <h2 id="skills">Skills & Tools:</h2>
					<ul class="skill-lst">
						<li class="sk">
							<p>Java</p>
						</li>
						<li class="sk">
							<p>Python 3</p>
						</li>
						<li class="sk">
							<p>HTML 5</p>
						</li>
						<li class="sk">
							<p>CSS</p>
						</li>
						<li class="sk">
							<p>Canva</p>
						</li>
						<li class="sk">
							<p>Power BI</p>
						</li>
						<li class="sk">
							<p>Microsoft Office</p>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</body>
</html>

{% endblock %}